### PR TITLE
Social Icon ui fixed 

### PR DESCRIPTION
**Pull request by anupammaurya6767**
#### Fixes #5 
      Fixes #5

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@anupammaurya6767 host website and share a live link. So I can review your changes.

**Comment by anupammaurya6767** [comment]
https://movie-streaming-website-omega.vercel.app/

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD use email and password for sign in as you are redirecting to your site in google sign in so it does not work

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD use email and password for sign in as you are redirecting to your site in google sign in so it does not work

yaa, that's another issue. Google Sign In.

**Pull request merged**
