### PR TITLE
Added dark/light theme

### PR DESCRIPTION
**Pull request by anupammaurya6767**
Added Dark light theme to home page.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@anupammaurya6767 host the website on Github pages or any other platform.

And share the live link so I can review your changes.

Also always link the issue with the pull requests like this  #22.

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD Here is the link : https://cute-beijinho-9c9ce7.netlify.app/home.html

**Comment by QAZIMAAZARSHAD** [comment]
@anupammaurya6767 issue was to add this feature on all pages(except the premium page), you have added this feature only on the home page.

Also, you have disturbed the navbar by adding the theme button. I suggest adding the theme change button in the footer. Also the design, size, and color of the theme button are not good.

Screenshot (326)
Here the background of the marquee tag is white even when the theme is dark.

**Comment by anupammaurya6767** [comment]
ok, i will fix it soon.
any other issue ?

**Comment by QAZIMAAZARSHAD** [comment]
> ok, I will fix it soon. any other issue?

No

**Pull request closed without merging**
