### PR TITLE
Created bollywood and hollywood sections for movie and webseries

### PR DESCRIPTION
**Pull request by Ritika091**
ISSUE #282 
fixes #

#### Describe the changes you've made
Created Bollywood and Hollywood sections for movies and webseries on the home page. Added movie posters and their details.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
1) Hollywood movie section
Screenshot (253)

2)Bollywood movie section
Screenshot (254)

3)Hollywood webseries section
Screenshot (255)

4)Bollywood webseries section
Screenshot (256)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Review your changes again, unnecessary addition of scroll to top section.

Only necessary changes should be there in your PR.

**Comment by Ritika091** [comment]
> Review your changes again, unnecessary addition of scroll to top section.
> 
> Only necessary changes should be there in your PR.

I just made changes only in the maincontainer ( <div class="maincontainer">) and just further subdivided the movies and webseries section into bollywood and hollywood. I didn't made any changes in that scroll to top section neither did I create it.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (139)


Check again.

Try making a new PR after fetch upstream. If you cannot resolve this.

**Comment by Ritika091** [comment]
> Screenshot (139)
> 
> Check again.
> 
> Try making a new PR after fetch upstream. If you cannot resolve this.

I have made the necessary changes in my code sir so you can check out.

**Comment by QAZIMAAZARSHAD** [comment]
Your repo is not updated.

Fetch upstream do only the necessary changes then make a new PR.

**Pull request closed without merging**
