### PR TITLE
bug solved of kid page

### LINKED ISSUE #449: Correct the color of genre drop down list in kids page
image

### PR DESCRIPTION
**Pull request by the-macson**
####Fixes #449

####I changed CSS of kids page and i currect background of genre drop down list

#### Checklist

- [X] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [X] The title of my pull request is a short description of the requested changes.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [LGMSoC] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@the-macson the hover colour is still different.

image


Make one more PR to correct it.

**Comment by the-macson** [comment]
> @the-macson the hover colour is still different.
> 
> image
> 
> Make one more PR to correct it.

Bug is about background colour that's i didn't see this . 
Okay assign me i will fix

**Comment by QAZIMAAZARSHAD** [comment]
I already awarded you points for this issue.

Just make a PR to correct this.

**Comment by the-macson** [comment]
> I already awarded you points for this issue.
> 
> Just make a PR to correct this.

ok

**Pull request merged**
