### PR TITLE
Fixed the lagg in redirecting to home page after signing in.

### PR DESCRIPTION
**Pull request by Anadee11**
#### Issue Number#317
fixes # Fixed the lagg in redirecting to homepage after signing in.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Do the same for signup.html

**Comment by QAZIMAAZARSHAD** [comment]
Always mention the issue number like this #317

**Comment by QAZIMAAZARSHAD** [comment]
@Anadee11 make the same changes in signup.html

**Comment by Anadee11** [comment]
okay sir, doing the same

**Comment by QAZIMAAZARSHAD** [comment]
You would have pushed the changes in the open PR from next time do the changes in the same PR if it is for the same issue.

**Pull request merged**
