### PR TITLE
trailer window inside website

### LINKED ISSUE #392: Trailer window should open within the website
Currently, when the trailer button is clicked the user is redirected to youtube, but instead a small or medium size window should open within the website to view the trailer.

### PR DESCRIPTION
**Pull request by dilroseR**
#### Describe the changes you've made
created a window which would open up inside the website 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

https://user-images.githubusercontent.com/70878223/127767391-5cf2d316-5150-441b-b58d-0cfdf2d508bd.mp4

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here): devincept participant

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
You have disturbed the position of the play and trailer button.

Add some spacing between the two.

**Comment by QAZIMAAZARSHAD** [comment]
And fetch upstream your repo is 1 commit behind.

**Comment by dilroseR** [comment]
done

**Comment by QAZIMAAZARSHAD** [comment]
What about other pages.

Genres - Crime, action, etc.

**Comment by QAZIMAAZARSHAD** [comment]
Apply on every page.

**Comment by dilroseR** [comment]
> Apply on every page.

oh okay i didn't see genres section. i'll do it that as well

**Comment by dilroseR** [comment]
let me know if anything is left to do

**Comment by QAZIMAAZARSHAD** [comment]
Share live demo link so I can review.

**Comment by dilroseR** [comment]
> Share live demo link so I can review.

https://frosty-williams-011002.netlify.app/

**Pull request merged**
