### PR TITLE
I have added the Hover effect on Navbar links

### PR DESCRIPTION
**Pull request by RituSingh2002**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@RituSingh2002 host your website on any platform like GitHub pages, netlify, or repl.it and share the deployment link for review.

**Comment by RituSingh2002** [comment]
@QAZIMAAZARSHAD  I m not able to deploy it on github But my code is working fine Could you merge it

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I m not able to deploy it on github But my code is working fine Could you merge it

Merging PR without reviewing the live demo is not good.
In case of any abnormal behavior, I will have to revert your PR.

Host on github pages its simple.

Go to settings -> Scroll down to Github pages -> You will get link.

**Comment by RituSingh2002** [comment]
> > @QAZIMAAZARSHAD I m not able to deploy it on github But my code is working fine Could you merge it
> 
> Merging PR without reviewing the live demo is not good.
> In case of any abnormal behavior, I will have to revert your PR.
> 
> Host on github pages its simple.
> 
> Go to settings -> Scroll down to Github pages -> You will get link.

@QAZIMAAZARSHAD  https://ritusingh2002.github.io/Movie-Streaming-Website/home.html (It's Done)

**Comment by QAZIMAAZARSHAD** [comment]
It's fine but you have applied the hover effect only on the home page.

**Comment by QAZIMAAZARSHAD** [comment]
And always mention issue number like this so the issue gets automatically closed.
Fixes #494

**Pull request merged**
