### PR TITLE
removed splash screen

### LINKED ISSUE #446: Remove splash screen from website

### PR DESCRIPTION
**Pull request by harshit-dugar**
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review the changes?

**Comment by harshit-dugar** [comment]
file:///Users/harshit/Desktop/Movie-Streaming-Website/home.html

**Comment by harshit-dugar** [comment]
How can I share my local html changes here ?
can you guide

**Comment by QAZIMAAZARSHAD** [comment]
> How can I share my local html changes here ?
> can you guide

Deploy website on GitHub pages or netlify then share the link.

**Comment by utkarsh-ub** [comment]
> How can I share my local html changes here ?
> can you guide

Please share the link @harshit-dugar

**Pull request closed without merging**
