### PR TITLE
Fix google sign-in function in login page

### PR DESCRIPTION
**Pull request by RituCs**
#### Issue Number
 

ISSUE #406
#### Describe the changes you've made

Added js code in login.html

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Test plan (OPTIONAL)
Please upload the project to  server before test.

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@RituCs share a link so that I can review whether it is working or not.

**Comment by RituCs** [comment]
> @RituCs share a link so that I can review whether it is working or not.

It is not possible .I have to host this project to show you it's working or not. I have checked this thing just create one sign in button and redirect with random page. And In this project after sign in it's redirect to https://qazimaazarshad.github.io/Movie-Streaming-Website/home.html.So for doing this I have to host .

**Comment by QAZIMAAZARSHAD** [comment]
@RituCs https://qazimaazarshad.github.io/Movie-Streaming-Website/login.html

check it's not working.

**Comment by RituCs** [comment]
> @RituCs https://qazimaazarshad.github.io/Movie-Streaming-Website/login.html
> 
> check it's not working.

Yeah I have Checked it's not working.Sorry for this. But Just check this https://60e83f456d13b.htmlsave.net/

**Comment by QAZIMAAZARSHAD** [comment]
This is working.

Figure out the bug.

**Comment by RituCs** [comment]
> This is working.
> 
> Figure out the bug.

Please check this https://ritucs.github.io/movie/ . Let me know if it's working or not.

**Comment by QAZIMAAZARSHAD** [comment]
> > This is working.
> > Figure out the bug.
> 
> Please check this https://ritucs.github.io/movie/ . Let me know if it's working or not.

Yaa working.

But the button size is different.

**Comment by carrollmark** [comment]
> > > This is working.
> > > Figure out the bug.
> > 
> > 
> > Please check this https://ritucs.github.io/movie/ . Let me know if it's working or not.
> 
> Yaa working.
> 
> But the button size is different.
Yes I will fix the button size.

**Comment by RituCs** [comment]
> > > This is working.
> > > Figure out the bug.
> > 
> > 
> > Please check this https://ritucs.github.io/movie/ . Let me know if it's working or not.
> 
> Yaa working.
> 
> But the button size is different.

I will fix this .

**Pull request merged**
