### PR TITLE
Updated latest accurate information of films

### PR DESCRIPTION
**Pull request by crimsenth**
#### Describe the changes you've made
Updated and added the latest accurate information in home page and all genre except anime page
Changed movie season into hour and minute format

#### Checklist

- [ ] I have mentioned related issue numbers in the PR description.
- [ ] I have added screenshots and related demo links of my changes.
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

**Comment by QAZIMAAZARSHAD** [comment]
@crimsenth are you a part of DCP or LGMSoC?

**Comment by crimsenth** [comment]
> @crimsenth are you a part of DCP or LGMSoC?

no.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

**Pull request merged**
