### PR TITLE
Landing page added

### PR DESCRIPTION
**Pull request by heyankit78**
Created a landing page for the website which will enhance the UI

#### Issue Number
fixed#38

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Always mention issue number like this #38

**Comment by heyankit78** [comment]
@QAZIMAAZARSHAD Okkayyy

**Comment by QAZIMAAZARSHAD** [comment]
@heyankit78 where is landpage.html. Where have you linked that page?

**Comment by heyankit78** [comment]
@QAZIMAAZARSHAD in stactic folder...and it is linked with index.html. 
Will i have to put outside of static?

**Comment by QAZIMAAZARSHAD** [comment]
No, I did not mean that.

I was asking how users will reach the landing page.

Show me the video or screenshot, how the user reaches the landing page and how is landing page.

**Comment by heyankit78** [comment]
I updated the landpage

**Comment by QAZIMAAZARSHAD** [comment]
Review your changes again.

When the website opens, index.html opens not landpage.html.

Also, you have written the wrong location of the index.html when play button is clicked.

**Pull request closed without merging**
