### PR TITLE
added the anime page

### PR DESCRIPTION
**Pull request by Srijan1878**
#### Issue Number
 

ISSUE #391 

#### Describe the changes you've made
Added the Anime page and made small changes accordingly like adding anime nav link to other page's navbar.
Also added the anime preview section in home page

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

NA

#### Additional context (OPTIONAL)
Screenshot (328)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
LGMSOC

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Srijan1878 share screenshots of the navbar as well.

**Comment by Srijan1878** [comment]
Navbar of the home page
Screenshot (329)

Navbar of the Anime page itself
Screenshot (330)

**Comment by QAZIMAAZARSHAD** [comment]
Have you added it in the navbar of the contact page?

**Comment by Srijan1878** [comment]
Just noticed that I have missed it in the contact us page. I have added it in the rest of the pages.
Should I add in the contact page? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Just noticed that I have missed it in the contact us page. I have added it in the rest of the pages.
> Should I add in the contact page? @QAZIMAAZARSHAD

Yes, the navbar of all pages should be the same.

**Comment by Srijan1878** [comment]
Okay.

**Comment by Srijan1878** [comment]
Was facing few conflicts, I have resolved it all and I guess it's okay now. I have also added the anime to navbar of the contact us page

**Comment by QAZIMAAZARSHAD** [comment]
@Srijan1878 do something about the navbar.

It is not fine.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (32)

**Comment by Srijan1878** [comment]
Screenshot (331)

I just checked, it's showing normal on my pc.
Please check it once more, if you still face it then let me know.

**Comment by QAZIMAAZARSHAD** [comment]
image


Maybe your window size is large that's why it is fine but it is not proper on all screens.

Correct it.

**Comment by Srijan1878** [comment]
Okay!

**Pull request merged**
