### PR TITLE
authentication  with google

### LINKED ISSUE #120: Google authentication
It helps user to login by google

### PR DESCRIPTION
**Pull request by Akshit42-hue**
#### Issue Number
fixes #120 

#### Describe the changes you've made
I have made google authentication 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
google authentication only works on localhost

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by Akshit42-hue** [comment]
@QAZIMAAZARSHAD can you please tell me sir what changes I have to made

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can you please tell me sir what changes I have to made

No changes.

Your repo is not updated that's why I cannot merge it.
Fetch upstream to make it even with my branch.

**Comment by Akshit42-hue** [comment]
> > @QAZIMAAZARSHAD can you please tell me sir what changes I have to made
> 
> No changes.
> 
> Your repo is not updated that's why I cannot merge it.
> Fetch upstream to make it even with my branch.

updated

**Comment by QAZIMAAZARSHAD** [comment]
Conflicts not resolved

**Comment by QAZIMAAZARSHAD** [comment]
@Akshit42-hue whenever you make new PR close the previous ones.

**Pull request closed without merging**
