### PR TITLE
Shivshankar9-patch-4

### PR DESCRIPTION
**Pull request by shivshankar9**
Issue #332

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Since you are adding new screenshots so no point in including old screenshots.

Replace old ones.

**Comment by QAZIMAAZARSHAD** [comment]
Needs improvement!!!!

In Home page screenshot - Show entire page, show hover effects on navbar, show flip effects and also open varieties drop down list.

Add search bar screenshot - Type a movie name, show the result then click on watch now and show that movie page (select a movie whose description page is bug free)

Sign up page - show otp verification function, and password validation

kids page - show entire page

Contact us page - show by filling form

Delete animated flip and animated footer

**Comment by QAZIMAAZARSHAD** [comment]
Make a new PR with these changes.

**Comment by shivshankar9** [comment]
Ok

**Pull request merged**
