### PR TITLE
Adding movie page and links

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
#### Issue Number
fixes #

ISSUE #163 
-->

#### Describe the changes you've made
Created a movie page with a slider and added 5 categories of movies and linking it with other pages

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
NA
#### Test plan (OPTIONAL)
Clicking on the links

#### Checklist

- [ x] I have added my name in the contributors list at the end of README.md file.
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by anushka-srivastava22** [comment]
@QAZIMAAZARSHAD Sir 
I am not able to figure out why this problem is being created when i added movie.html in other files why files are conflicting. Yesterday I spent 5 hours to find the solution. Today also I spent 3 hours but the issue is still not resolved.

**Comment by QAZIMAAZARSHAD** [comment]
Maybe your repo is not updated. Fetch upstream then push changes.

Add only necessary changes, don't change anything.

**Comment by anushka-srivastava22** [comment]
Everytime before i push file , I clone the new repo and add the movie page and only change the links of every page to movie.html . And then i create a pull request. After that i resolve the conflicts for half an hour but then also🥺🥺🥺 Is there any other way or resource to do it ?

**Comment by QAZIMAAZARSHAD** [comment]
Reach out to mentors in slack channels they will help you in resolving issues.

**Comment by anushka-srivastava22** [comment]
Okay Sir

**Pull request closed without merging**
