### PR TITLE
Add appropriate font-family to website

### PR DESCRIPTION
**Pull request by sanketcharanpahadi**
fixes isuue no #20

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Font of kids, tv, and web series page is still different. Also font of the footer is different.

Do the necessary changes.

**Comment by sanketcharanpahadi** [comment]
@QAZIMAAZARSHAD can you look at it if it has any problems?

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (110)

It has created another issue, look into this.

**Comment by sanketcharanpahadi** [comment]
@QAZIMAAZARSHAD okay.

**Comment by sanketcharanpahadi** [comment]
image

**Comment by sanketcharanpahadi** [comment]
is it good now @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> is it good now @QAZIMAAZARSHAD

Still same

**Comment by sanketcharanpahadi** [comment]
what should I do now @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
Change the font only.

It should not change anything else like spacing, alignment, etc.

**Comment by sanketcharanpahadi** [comment]
@QAZIMAAZARSHAD ok i will try again

**Pull request closed without merging**
