### PR TITLE
Fix the google sign in bug  #406

### LINKED ISSUE #406: Fix google sign-in function in login page

### PR DESCRIPTION
**Pull request by RituCs**
#### Fixes #(issue number)

 Fixes #406 

#### Describe the changes you've made
Changes html,js code in login.html

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by RituCs** [comment]
Check this https://ritucs.github.io/movie @QAZIMAAZARSHAD . I have changed the button size.

**Comment by QAZIMAAZARSHAD** [comment]
Check again it is jumping to the home page from the login page without doing anything.

**Comment by RituCs** [comment]
> Check again it is jumping to the home page from the login page without doing anything.

It is happening because you already signed in. Try it incognito or private mode in your browser.

**Comment by QAZIMAAZARSHAD** [comment]
No in incognito it is not redirecting anywhere.

**Comment by RituCs** [comment]
> No in incognito it is not redirecting anywhere.

so it's ok . Right? It's redirecting because browser saves your details when you signed in. There is no signed out button and your data is saved so that's why it's redirecting.

**Comment by QAZIMAAZARSHAD** [comment]
No, not right.

I mean it is not working in Incognito.

**Comment by RituCs** [comment]
> No, not right.
> 
> I mean it is not working in Incognito.
It's perfectly working for me.
Which browser you are using? In some browser like chrome in private mode, they block the cookies. Be sure you enable third party cookies.

**Comment by QAZIMAAZARSHAD** [comment]
@ishi0301 and @saimanoharhm review this PR.

**Review by saimanoharhm — COMMENTED** [review]
It's working for me.  @QAZIMAAZARSHAD Here is the screenrecording.
Link:- https://drive.google.com/file/d/1SZFWxCc5pPTVdi_TA4bM4OFmvVK1U8Rb/view?usp=sharing

**Pull request merged**
