### PR TITLE
Added a coming soon slider and also a news section

### LINKED ISSUE #106: Add news and coming soon section
news and comingsoon
   
can i get assign to it?

### PR DESCRIPTION
**Pull request by Srijan1878**
####fixes(#106 )
 

 

#### Describe the changes you've made
 I have added Coming soon slider on the front page and also added a news section based on the upcoming movies and other news as well
Screenshot (349)
Screenshot (350)

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)LGMSOC

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Srijan1878 share a deployment link so I can review your changes.

**Comment by Srijan1878** [comment]
Okay

**Comment by Srijan1878** [comment]
https://gracious-austin-591312.netlify.app/

Here's the site link.

**Comment by QAZIMAAZARSHAD** [comment]
Check the font of Coming Soon.

image
image
Correct navbar

**Comment by QAZIMAAZARSHAD** [comment]
@Srijan1878 any updates?

Fetch upstream and ping me when you resolve all the issues.

**Comment by Srijan1878** [comment]
I resolved them, have a look!

**Comment by QAZIMAAZARSHAD** [comment]
@Srijan1878 share an updated link.

Add a footer to the news page. 
Remove the news slideshow from the homepage.
Update the navbars of all the pages.

**Comment by QAZIMAAZARSHAD** [comment]
I suggest don't add news in the navbar add it in the footer.

Add it



> @Srijan1878 share an updated link.
> 
> Add a footer to the news page.
> Remove the news slideshow from the homepage.
> No changes in the navbar.

**Comment by Srijan1878** [comment]
Okay! @QAZIMAAZARSHAD

**Pull request closed without merging**
