### PR TITLE
redesigned home page

### LINKED ISSUE #19: Improve/Redesign home page
Can I Redesign the home page . 
@QAZIMAAZARSHAD  please assign this issue to me.

### PR DESCRIPTION
**Pull request by coding-geek21**
#### Issue Number
fixes #19 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Please do check the design of the page here
I have made changes to the body section only , I saw many issues related to navbar and footer , so I didn't change them 
I made it similar to #35 So that every page has the same theme
Thank you :)

https://screenrec.com/share/nO5YdRvT2t

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 resolve conflicts.

**Comment by coding-geek21** [comment]
Sure

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD  I have resolved the conflicts please do check it :)

**Comment by QAZIMAAZARSHAD** [comment]
Not resolved.

Update your repo then make new PR.

**Pull request closed without merging**
