### PR TITLE
logo added in about section

### LINKED ISSUE #204: Add logo in readme
@QAZIMAAZARSHAD  pls assign  this issues

### PR DESCRIPTION
**Pull request by rishabhrathore055**
#### Issue Number
fixes #204

#### Describe the changes you've made
Add a logo in about section and align it center

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by rishabhrathore055** [comment]
@QAZIMAAZARSHAD Check it once it's perfect or not

**Comment by QAZIMAAZARSHAD** [comment]
No not fine, add the logo in place of the blue box and text in place of the green box side by side.
Also, upload that logo.png file inside images/Logo folder.
Screenshot (115)

**Comment by rishabhrathore055** [comment]
@QAZIMAAZARSHAD okay

**Comment by rishabhrathore055** [comment]
@QAZIMAAZARSHAD i will create new PR very soon

**Pull request closed without merging**
