### PR TITLE
updated

### PR DESCRIPTION
**Pull request by Akshit42-hue**
#### Issue Number
fixes #

#### Describe the changes you've made
I have made google authentication
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
google authentication only works on localhost

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Akshit42-hue always mention the issue number in description #120.

**Comment by QAZIMAAZARSHAD** [comment]
@Akshit42-hue share a live demo link.

**Comment by saimanoharhm** [comment]
@Akshit42-hue There is a conflict as well. Please have a look at it.

**Comment by Akshit42-hue** [comment]
Please do have a look here is the video link
[https://drive.google.com/file/d/1ZLiPqUGjlLkKoliNSifJaxpTTWf42M0o/view?usp=sharing](url)

**Comment by QAZIMAAZARSHAD** [comment]
> Please do have a look here is the video link
> [https://drive.google.com/file/d/1ZLiPqUGjlLkKoliNSifJaxpTTWf42M0o/view?usp=sharing](url)

No not like this.

Don't disable any existing feature add a button of sign in with google below sign in button.
Screenshot (3)

Like this.



Abd your repo is not updated, fetch upstream first make changes and make PR,

**Pull request closed without merging**
