### PR TITLE
Added dropdown of Genres below navbar

### LINKED ISSUE #267: Remove the "Have a look on various movies" drop down and add drop down list of all genres in navbar
Screenshot (894)

### PR DESCRIPTION
**Pull request by wc0801**
#### Describe the changes you've made
Remove the current "Have a look on various movies" and add the genre dropdown below nav bar. If put inside nav bar, the dropdown will expand inside the nav bar.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Shift it in the navbar,

**Comment by wc0801** [comment]
image
Is this okay?

**Comment by QAZIMAAZARSHAD** [comment]
Shift on the right side of contact

**Comment by wc0801** [comment]
image

**Comment by QAZIMAAZARSHAD** [comment]
Increase the size a bit so the text should be equal to other items in the navbar.

Also, check responsiveness in mobile.

**Comment by QAZIMAAZARSHAD** [comment]
Also replace the pink, white, and that brown color with website theme colors like red-black-white.

**Comment by wc0801** [comment]
image
image

**Comment by QAZIMAAZARSHAD** [comment]
Replace brown color with black.

**Comment by wc0801** [comment]
image

**Comment by QAZIMAAZARSHAD** [comment]
Fine share the website link so I can review your changes.

**Comment by wc0801** [comment]
https://wc0801.github.io/Movie-Streaming-Website/home.html

**Comment by QAZIMAAZARSHAD** [comment]
You are part of DCP or LGMSoC.

**Comment by wc0801** [comment]
No

**Comment by QAZIMAAZARSHAD** [comment]
Neither DCP nor LGMSoC?

**Comment by wc0801** [comment]
Neither of them

**Pull request merged**
