### PR TITLE
To enhance the UI of Login

### LINKED ISSUE #104: Improve login page design
I would like to enhance the UI of Login Page as keeping in mind the current theme 
Please assign me this issue.

### PR DESCRIPTION
**Pull request by ish-0709**
#### Issue Number
fixes #104

#### Describe the changes you've made

- Completely changed the UI of the Login/Sign-In page.

   - Added a footer to the page which contains question section linked to the gmail.
   - The footer has FAQ , Help Centre, Privacy ,Terms of Use as well as a language markup box
   - Added a new logo to the page
   -  Added a new background which is the exact image of the main page

 
- Added a new Sign Up link which takes the user to a new sign up page.

  - Also added a new sign-up page for new users which is linked from the login page.
   - The new page has name,email,password and re-enter the same password which takes only those inputs which are validated by the below mentioned statements/warnings

- Added a new script.js file in js folder
- Added a new style.css file in style folder
- Added images to Image folder
- Changed the logo as well to make it suit according to the page colors. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

https://user-images.githubusercontent.com/63011793/121699740-d2a42f00-caec-11eb-89de-df2cdd790cf3.mp4

#### Test plan (OPTIONAL)

- Simply go to the Login navigation bar from the main page and click on it.
- From here if you are a new user make a new account by clicking the Sign up now link
- If you are an old user simply enter the login details.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program : Lets Grow More

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Nice @ish-0709.

Try to resolve conflicts.

Also, as soon as a user signs up or login it should redirect to quiz.html.

Review your changes, fetch upstream and make a new PR.

**Comment by QAZIMAAZARSHAD** [comment]
Make a new PR. After updating your repo.

It may solve the issue.

**Comment by ish-0709** [comment]
Okay sir

**Comment by ish-0709** [comment]
Sir I dont understand this I am not able to pull the new request again

**Pull request closed without merging**
