### PR TITLE
Scroll to top button

### PR DESCRIPTION
**Pull request by jugeshraghav**
#### Issue Number
fixes #
#278 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by jugeshraghav** [comment]
please look at it and review it. @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
The website has been updated a lot.

Index.html is now home.html, do the changes again and resolve the conflicts.

**Comment by jugeshraghav** [comment]
Okay

**Comment by jugeshraghav** [comment]
changes are done in the scroll button in all the pages.

**Comment by jugeshraghav** [comment]
please have a look @QAZIMAAZARSHAD

**Pull request merged**
