### PR TITLE
image slider effect is created in the home section.

### LINKED ISSUE #56: Add movie card sliders with handles
Instead of displaying whole content for a particular movie genre we can add card slider so that user can click on it to view cards on left side and right side 

@QAZIMAAZARSHAD  I would like to work on this please assign me ,

### PR DESCRIPTION
**Pull request by jugeshraghav**
#### Issue Number
fixes #56 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by jugeshraghav** [comment]
@QAZIMAAZARSHAD  please look at it and suggest me if any changes are possible.

**Comment by QAZIMAAZARSHAD** [comment]
Share a screenshot and live demo link,

**Comment by jugeshraghav** [comment]
https://user-images.githubusercontent.com/74092377/123508244-ca6ef680-d68b-11eb-9e73-49887328fa66.mp4

this feature is implemented.

**Comment by jugeshraghav** [comment]
on clicking the buttons the images will scroll left and right.

**Comment by jugeshraghav** [comment]
https://user-images.githubusercontent.com/74092377/123508354-803a4500-d68c-11eb-992e-30d23a1b302f.mp4

**Comment by QAZIMAAZARSHAD** [comment]
Apply this on every page, every section.

Check flip effect and responsiveness as well.

**Comment by jugeshraghav** [comment]
Okay

**Comment by jugeshraghav** [comment]
Hi @QAZIMAAZARSHAD  I was thinking to change the buttons from circular shape to rectangular shape. what do you think about it?

**Comment by QAZIMAAZARSHAD** [comment]
Sure,

Try to make it transparent, or unnoticeable like on the kids' page. You can do whatever you want as long as it looks nice.

**Comment by saimanoharhm** [comment]
@jugeshraghav Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by jugeshraghav** [comment]
hii @QAZIMAAZARSHAD  I have created the slider in all the pages where it was needed. please have a look  and suggest me changes if there.

**Comment by jugeshraghav** [comment]
@saimanoharhm i don,t know how but the problem is resolved. Thank you so much.

**Comment by QAZIMAAZARSHAD** [comment]
@jugeshraghav share the website link so I can review your changes.

**Pull request closed without merging**
