### PR TITLE
redesigned landing page

### LINKED ISSUE #316: Redesign landing page
Improve design, CSS, and background of index.html.

### PR DESCRIPTION
**Pull request by Godwindaniel10**
#### Issue Number
fixes #316 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

Also share a live demo link to your website.

**Comment by Godwindaniel10** [comment]
hi @QAZIMAAZARSHAD ,  conflicts resolved, but i don't understand what you mean by ( live demo link to my website ).

**Comment by QAZIMAAZARSHAD** [comment]
> hi @QAZIMAAZARSHAD , conflicts resolved, but i don't understand what you mean by ( live demo link to my website ).

https://qazimaazarshad.github.io/Movie-Streaming-Website/

Like this so, I can see your changes.

**Comment by QAZIMAAZARSHAD** [comment]
image

This is what you intended?

**Comment by Godwindaniel10** [comment]
Yes

**Comment by Godwindaniel10** [comment]
Any changes you want , i am available for that.

**Comment by QAZIMAAZARSHAD** [comment]
image

https://qazimaazarshad.github.io/Movie-Streaming-Website/

Check it and improve.

**Comment by Godwindaniel10** [comment]
Aiit

**Comment by Godwindaniel10** [comment]
SHould i push the changes to this branch or a new one?

**Comment by Godwindaniel10** [comment]
video of the landing page 
https://user-images.githubusercontent.com/54848535/123241116-c77fd480-d4d8-11eb-982b-b804332a653e.mp4

**Comment by QAZIMAAZARSHAD** [comment]
> SHould i push the changes to this branch or a new one?

You have to make a new PR.

**Pull request merged**
