### PR TITLE
Made Premium page responsive

### LINKED ISSUE #488: Check responsiveness in premium page
Also add scroll to top button

### PR DESCRIPTION
**Pull request by Swastik1710**
#### Describe the changes you've made
Made the Premium page mobile responsive.

#### Deploy your changes to github page or netlify and mention deployment link:
https://swastik1710.github.io/Movie-Streaming-Website/

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - DCP 2021

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

Add coming soon in the footer.

**Comment by Swastik1710** [comment]
I didn't get you!

**Comment by QAZIMAAZARSHAD** [comment]
> I didn't get you!

Footer has been updated compare with other footers.

**Comment by Swastik1710** [comment]
Done !

**Pull request merged**
