### PR TITLE
Movie Cards

### LINKED ISSUE #126: Add more database(more content)
Hey @QAZIMAAZARSHAD 
I would like to add more database to it.
If possible please assign it to me.
Thanks

### PR DESCRIPTION
**Pull request by Shaishav0507**
#### Issue Number
fixes #126 

#### Describe the changes you've made
Hey @QAZIMAAZARSHAD 
I have lot of movie cards with same image resolution.
Thanks for letting me work.

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD 
Please check and let me know.

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by Shaishav0507** [comment]
I'm not authorised to resolve.

**Comment by QAZIMAAZARSHAD** [comment]
Their is also a slight difference in size. See


chernobyl

**Comment by QAZIMAAZARSHAD** [comment]
> Their is also a slight difference in size. See
> 
> 
> chernobyl

Try to work it out

**Comment by Shaishav0507** [comment]
Ok

**Comment by QAZIMAAZARSHAD** [comment]
> I'm not authorised to resolve.

Solve the size difference problem and create a new PR it may solve the conflict.

**Pull request closed without merging**
