### PR TITLE
Enhance Tagline by Hovering Effects

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
#### Issue Number
fixes #

ISSUE #161  

#### Describe the changes you've made
Added a text shadow effect on hovering on the tagline of front page

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Shades of orange  has been used for text shadow.

#### Test plan (OPTIONAL)
On hovering the tagline , text shadow can be seen

#### Checklist

- [ x ] I have added my name in the contributors list at the end of README.md file.
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] The title of my pull request is a short description of the requested changes.
- [ x ] Open Source Program names

### CODE REVIEW

**Comment by anushka-srivastava22** [comment]
Sir, 
I have resolved all the errors, bugs & problems in this pull request. the error was space between heading and braces.

**Comment by anushka-srivastava22** [comment]
@QAZIMAAZARSHAD 
Please , Kindly review this last pull request. this doesn't have any problem.

**Comment by QAZIMAAZARSHAD** [comment]
This is perfectly fine.

Always make PR's like this.

**Comment by anushka-srivastava22** [comment]
Thank you sir. I have learned one new thing today to check those bars on the top.

**Comment by QAZIMAAZARSHAD** [comment]
Keep learning.

**Comment by anushka-srivastava22** [comment]
Yeah Sir Surely 💯

**Pull request merged**
