### PR TITLE
Update login.html

### PR DESCRIPTION
**Pull request by Anjali1806**
I have edited login page

#180 
fixes ISSUE #180
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by QAZIMAAZARSHAD** [comment]
Resolve comflicts.

**Review by Anjali1806 — COMMENTED** [review]
conflict resolved now.
Login page updated.

**Comment by QAZIMAAZARSHAD** [comment]
@Anjali1806 can you tell what changes you have done in this PR.

You have only changed sign-in to sign up and nothing else. 
And have tried to set the old logo as a background image which is not working.

**Comment by Anjali1806** [comment]
I tried to add javascript code in form but that  didn't worked due to
technical issue in my editor.

**Pull request closed without merging**
