### PR TITLE
redesigned the home-page in index.html and added some more higher qua…

### LINKED ISSUE #316: Redesign landing page
Improve design, CSS, and background of index.html.

### PR DESCRIPTION
**Pull request by Godwindaniel10**
…lity movie posters

#### Issue Number
fixes #316 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Godwindaniel10 I think you are not aware of the updated website.

Review your changes and make PR only for the related issue.

**Comment by Godwindaniel10** [comment]
Hi @QAZIMAAZARSHAD , ok but you said index.html file.

**Comment by QAZIMAAZARSHAD** [comment]
> Hi @QAZIMAAZARSHAD , ok but you said index.html file.

That was before the update, a landing page is now index.html and the homepage is home.html.

Always keep yourself updated.

**Comment by Godwindaniel10** [comment]
Right

**Comment by Godwindaniel10** [comment]
@QAZIMAAZARSHAD i will update and fix the issue .

**Pull request closed without merging**
