### PR TITLE
splash screen

### LINKED ISSUE #281: Improving splash screen

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #281 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

Also, your PR doesn't look clean.

**Comment by kumarishalini6** [comment]
Do you have any design in your mind , I don't have any effect for logo.

**Comment by kumarishalini6** [comment]
> Resolve conflicts.
> 
> Also, your PR doesn't look clean.

Resolved conflicts

**Comment by kumarishalini6** [comment]
> Resolve conflicts.
> 
> Also, your PR doesn't look clean.

PR doesn't look clear means ??

**Comment by QAZIMAAZARSHAD** [comment]
> > Resolve conflicts.
> > Also, your PR doesn't look clean.
> 
> PR doesn't look clear means ??

There were so many unnecessary additions and deletions.

**Comment by QAZIMAAZARSHAD** [comment]
Conflicts still not resolved.

**Comment by kumarishalini6** [comment]
> > > Resolve conflicts.
> > > Also, your PR doesn't look clean.
> > 
> > 
> > PR doesn't look clear means ??
> 
> There were so many unnecessary additions and deletions.

yes because I have add index.html file and rename index.html to home .html  for resolving the splash screen's bug

**Comment by QAZIMAAZARSHAD** [comment]
https://movie-streaming-website-1.qazimaazarshad.repl.co/

This is the website after your changes.

You have removed landing page, and the splash screen again appears every time when the user goes to the home screen.
And the design is very poor. Lack responsiveness.

Add splash screen only one time when user logins and if signs up display after the quiz.


Try again keeping these things in mind.

**Pull request closed without merging**
