### PR TITLE
All Buttons Linked Correctly

### LINKED ISSUE #168: Linking Of Button Is Not Done Correctly With The Correct Html Page
I would like to work on this issue.

**Changes I Will Do : **
1. Link all the pages in the website on each and every page correctly.

### PR DESCRIPTION
**Pull request by JatanDudeja**
#### Issue Number
fixes #168 

#### Describe the changes you've made
I have linked all the html files with the correct buttons and have also tested it thoroughly.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] The title of my pull request is a short description of the requested changes.
- [X] Open Source Program names(LetsGrowMore)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Good.

Also add contactus.html in every page.

**Comment by JatanDudeja** [comment]
Can I please make another pr for this contact us because on the issue it was not mentioned?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I please make another pr for this contact us because on this issue was not mentioned?

okk

**Comment by JatanDudeja** [comment]
Okay

**Pull request merged**
