### PR TITLE
Update signup.html

### LINKED ISSUE #392: Trailer window should open within the website
Currently, when the trailer button is clicked the user is redirected to youtube, but instead a small or medium size window should open within the website to view the trailer.

### PR DESCRIPTION
**Pull request by bansiparsania**
fixes #392 
ISSUE #348  

#### Describe the changes you've made
1.  change align to center  in input text  after verification form.
2.  change width: 100% of password code in verification code .
3. change align to center in signin register button.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
nothing.

#### Test plan (OPTIONAL)
nothing 
#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Review by bansiparsania — COMMENTED** [review]
plz accept my PR

**Comment by QAZIMAAZARSHAD** [comment]
@bansiparsania always mention only one and correct issue number,

No point in mentioning issue 392.

**Comment by bansiparsania** [comment]
Okay

**Comment by QAZIMAAZARSHAD** [comment]
@bansiparsania issue not resolved.

image

Do again.

And review your changes before making PR next time.

**Comment by bansiparsania** [comment]
I trying to review but in vscode not getting perfect output when I signup I didn't get verification code what to do ?

**Comment by QAZIMAAZARSHAD** [comment]
> I trying to review but in vscode not getting perfect output when I signup I didn't get verification code what to do ?

Use Repl.it

**Pull request merged**
