### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by ekagrashukla**
#### Fixed Issue #5 

Created a Cool looking minimal footer with fluid water droplet effect, that perfectly matches with the dark theme of the website.

github_footer

P.S. In this GIF, it is looking jittery due to frame rate, but actually it's way fluid. :)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Fine,

But try replacing the gray color with red.
Show me here.

**Comment by ekagrashukla** [comment]
image

This is how it looks in red.
Shall I change it?

**Comment by QAZIMAAZARSHAD** [comment]
No, it's fine.

Change text color from white to black.

**Comment by ekagrashukla** [comment]
Made the required changes 👍
(Changed footer color to red and footer font color to black).

**Comment by QAZIMAAZARSHAD** [comment]
It looks bad.

The first one was better.

**Comment by QAZIMAAZARSHAD** [comment]
> #### Fixed Issue #5
> Created a Cool looking minimal footer with fluid water droplet effect, that perfectly matches with the dark theme of the website.
> 
> github_footer
> 
> P.S. In this GIF, it is looking jittery due to frame rate, but actually it's way fluid. :)

Change it to this again for the final time.

No more changes.

**Comment by ekagrashukla** [comment]
Yup even I was thinking the same :)
sure I'll do that

**Comment by ekagrashukla** [comment]
Reverted back the changes @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@ekagrashukla make these changes in all the pages.

You have made it only in index.html

**Comment by QAZIMAAZARSHAD** [comment]
I have reverted these changes, make PR again.

**Comment by ekagrashukla** [comment]
My bad! I really forgot this.
Working on it 👍

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Pull request merged**
