### PR TITLE
Button Cutomised for REVIEW  (Search button in home page).

### LINKED ISSUE #381: Button improvement !
Heyy , I want to improve the buttons on the landing page and other pages . I am a LGM SOC'21 participant . 
Can I work on this ?

### PR DESCRIPTION
**Pull request by Sarthakjain594**
#### Issue Number
fixes #381 

#### Describe the changes you've made
 I have chnaged the search button in home page .Pls reveiw it further customisation in other buttons.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names:LGM SOC'21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
You have changed only in home.html.

Do it on all pages.

Also share a screenshot or live demo link.

**Comment by QAZIMAAZARSHAD** [comment]
@Sarthakjain594 are you doing the changes?

**Comment by saimanoharhm** [comment]
@Sarthakjain594 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by QAZIMAAZARSHAD** [comment]
@Sarthakjain594 should I close PR and issue or are you still working on it.

**Pull request closed without merging**
