### PR TITLE
Designed new Preloader

### PR DESCRIPTION
**Pull request by aasthasaxena217**
#466 
Designed and applied new preloader
You can Check here: https://aasthasaxena217.github.io/Movie-Streaming-Website/

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@aasthasaxena217 resolve conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
Your branch is 22 commits behind, fetch upstream.


And please review your code, there are some unnecessary changes in other files.

**Comment by QAZIMAAZARSHAD** [comment]
And the design is really nice.

Great work.

**Comment by aasthasaxena217** [comment]
Thanks @QAZIMAAZARSHAD , I am happy you like it :)

**Pull request merged**
