### PR TITLE
Aligned the Text

### LINKED ISSUE #198: Beautify the content in each File
Hey @QAZIMAAZARSHAD 
I would like to align the text and make it more readable.
Please assign it to me.
Thanks

### PR DESCRIPTION
**Pull request by Shaishav0507**
#### Issue Number
fixes #198 

#### Describe the changes you've made
Hey @QAZIMAAZARSHAD 
I aligned the text to the best I could do.
Please check and Update.
Thanks.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

Also share the live demo link if possible.

**Comment by Shaishav0507** [comment]
Ok I'll do

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD 
Not able to figure out what conflict is there.
It would be great, if you could help me.

**Comment by QAZIMAAZARSHAD** [comment]
Conflicting files
action.html
comedy.html
contactus.html
crime.html
documentary.html
drama.html
dummy.html
fantasy.html
horror.html
index.html
popular.html
romance.html
suspense.html
tv.html
war.html
web-series.html

**Comment by QAZIMAAZARSHAD** [comment]
Update your repo, fetch upstream.

Then pusg changes then make a new PR.

**Comment by Shaishav0507** [comment]
OK I'll do

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD 
I think this issue is already resolved by someone else.
You can close this issue.
I'll try for other one.

**Pull request closed without merging**
