### PR TITLE
Added a movie page and linked it with other pages

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
#### Issue Number
fixes #
ISSUE #163 

#### Describe the changes you've made
Added a separate movie page with a slider below the nav bar with 5 categories of movies like top picks , popular e.t.c. and linked it with all other pages

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Additional context (OPTIONAL)
NA

#### Test plan (OPTIONAL)
Clicking on the links will work. I have tested it .

#### Checklist

- [ x ] I have added my name in the contributors list at the end of README.md file.
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] The title of my pull request is a short description of the requested changes.
- [ x ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by anushka-srivastava22** [comment]
Ya i am doing that only

**Comment by anushka-srivastava22** [comment]
sir I need a little time more to go through it.

**Comment by QAZIMAAZARSHAD** [comment]
> sir I need a little time more to go through it.

Take all the time.

**Pull request closed without merging**
