### PR TITLE
removed simple alert

### LINKED ISSUE #347: Not redirecting to quiz.html after successful sign up

### PR DESCRIPTION
**Pull request by dilroseR**
Fixes #347 
removed simple alert

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by dilroseR** [comment]
> Resolve conflicts.

resolved and kindly put DCP label in both of my PR

**Comment by QAZIMAAZARSHAD** [comment]
> > Resolve conflicts.
> 
> resolved and kindly put DCP label in both of my PR

No.

Only one PR will have the label because these 2 are for the same issue.

**Comment by dilroseR** [comment]
> > > Resolve conflicts.
> > 
> > 
> > resolved and kindly put DCP label in both of my PR
> 
> No.
> 
> Only one PR will have the label because these 2 are for the same issue.

oh alright

**Pull request merged**
