### PR TITLE
Alert Popup Box feature in contact form imported successfully

### PR DESCRIPTION
**Pull request by ROHAN842**
#### Issue Number
ISSUE #254 

#### Describe the changes you've made
I added an alert which will pops up and will tell the user that message was delivered successfully with a green tick along with I also added a feature without back end with which user would be sent to a fresh new page on clicking Send Message button where the message will be written, as "Thank you we received your submission , Return ".

#### Additional context (OPTIONAL)

https://user-images.githubusercontent.com/61961107/122243245-981e0600-cee1-11eb-998a-3506fd8fd13c.mp4

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by ROHAN842** [comment]
I had resolved could you please check now

**Comment by QAZIMAAZARSHAD** [comment]
@ROHAN842 this is the website after your changes https://movie-streaming-website-2.qazimaazarshad.repl.co/contactus.html.

Carefully review your changes, first update your repo, fetch upstream then push changes.

**Comment by ROHAN842** [comment]
OK

**Comment by QAZIMAAZARSHAD** [comment]
I am closing this PR, make a new PR.

Everything perfect.

**Pull request closed without merging**
