### PR TITLE
Another branch : Added logout feature functionality.

### PR DESCRIPTION
**Pull request by anupammaurya6767**
#482 Issue resolved

### CODE REVIEW

**Comment by anupammaurya6767** [comment]
Here is the link for same : https://snazzy-basbousa-23703a.netlify.app/

**Comment by QAZIMAAZARSHAD** [comment]
@anupammaurya6767 

image


You have generated some errors in the google sign-in.

**Comment by anupammaurya6767** [comment]
yes i saw that i think its because of site deployment. Let me check one more time

**Comment by QAZIMAAZARSHAD** [comment]
Also, the logout button should be redirected to the login page, you have redirected it to the index page.

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD where is google auto sign in function code , in which file?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD where is google auto sign in function code , in which file?

login.html

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD which url you provided in google cloud console for redirecting?

**Comment by QAZIMAAZARSHAD** [comment]
This is the issue:

Whenever a user is signed in via google it gets signed in automatically every time he opens login.html.

After clicking the logout button user must be logged out. And had to sign in again to proceed further.

**Comment by anupammaurya6767** [comment]
@QAZIMAAZARSHAD auto sign in does not work because you are not included the url of the my server in the Authorized Javascript Origins. You may simply add my url in authorised javascript origins of google cloud console or just add log.js file in your server it will work.

**Pull request merged**
