### PR TITLE
Compressed files

### PR DESCRIPTION
**Pull request by shivshankar9**
#387

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Not done!!!!!!!

**Comment by shivshankar9** [comment]
I tried to compress, after now t's above 30mb

**Comment by QAZIMAAZARSHAD** [comment]
???

**Comment by shivshankar9** [comment]
Can I revert back if there is any error

**Comment by QAZIMAAZARSHAD** [comment]
No error,

Just compress every file, below 10Mb and delete current files and upload new files.

Also, try to convert video in 2x speed it is very slow, it will also reduce the duration.

**Comment by shivshankar9** [comment]
Okay I will,
And also,
I already loosed my all data for now I will do it later ...

**Comment by QAZIMAAZARSHAD** [comment]
Yaa, that's happening to everyone that's why I told you to do it ASAP.

Try to do it ASAP and reduce the size to the least possible.

**Comment by shivshankar9** [comment]
Ok

**Pull request merged**
