### PR TITLE
Cursor added while hovering on the movies

### LINKED ISSUE #114: Changing Mouse Pointer When Hovering Over Movies
When hovering over movies the cursor remains as it is so it does not look like the the movie is clickable so I will change the default cursor to a pointer(hand mouse pointer).

### PR DESCRIPTION
**Pull request by JatanDudeja**
#114

#### Issue Number 
fixes #114 

#### Describe the changes you've made
1. Changed id web series from id = "Web Series" to id. = "WebSeries" in index.html.
2. Added cursor = pointer while hovering on the images in static/style.css.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] The title of my pull request is a short description of the requested changes.
- [X] Open Source Program names(LetsGrowMore)

### CODE REVIEW

**Review by MathurUtkarsh — APPROVED** [review]

**Comment by QAZIMAAZARSHAD** [comment]
@JatanDudeja not working on kids and tv page.

**Comment by JatanDudeja** [comment]
Okay I will check again do the necessary changes if required.

**Comment by JatanDudeja** [comment]
Please add this I will make another PR for these two pages.

**Comment by QAZIMAAZARSHAD** [comment]
> Please add this if possible. I will make another PR for these two pages.

Okk

**Pull request merged**
