### PR TITLE
Removed Checklist point from pull_request_template.md

### LINKED ISSUE #436: Update pull_request_template.md
This point in the checklist :

(I have added my name in the contributors list at the end of README.md file.)

is obsolete. So it is wise to remove it.

@QAZIMAAZARSHAD please assign this to me under DCP21

### PR DESCRIPTION
**Pull request by manasb15**
Fixes #436 

Removed a redundant checklist point from pull_request_template.md

DCP21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15 if you want to score points fill the form.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD I filled the form back then. Should i fill it again?

**Comment by QAZIMAAZARSHAD** [comment]
You have not filled for this one.

Fill for those where I have pinged you.

**Comment by manasb15** [comment]
> You have not filled for this one.
> 
> Fill for those where I have pinged you.

Yes I filled the forms just now. You can check to confirm.

**Comment by QAZIMAAZARSHAD** [comment]
In voters portal?

**Comment by manasb15** [comment]
> In voters portal?

Yeah, I filled all the forms of the PRs in which you commented today.

**Comment by QAZIMAAZARSHAD** [comment]
One left in voters portal check

**Comment by manasb15** [comment]
> One left in voters portal check

Ya filled it just now. Thanks.

**Pull request merged**
