### PR TITLE
Fix a small spelling mistake in Readme.md.

### PR DESCRIPTION
**Pull request by vishalps2606**
I came here by LGM-soc and found a small spelling error so I fixed it.

Open source name - LGM-SOC
There is no issue regarding this.
The code works properly.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Thanks, @vishalps2606.

But you won't get any points in LGM-SOC if you make PR's like this.
First, you have to open an issue and ask the project admin to assign you that issue. Once you are assigned then make PR, and always mention the issue number in the PR description.

**Comment by QAZIMAAZARSHAD** [comment]
If you want to score points then open an issue "Fix a typo error". Then edit your PR description with that issue number.

If you don't want to score points then tell me I will merge this PR.

**Comment by vishalps2606** [comment]
> Thanks, @vishalps2606.
> 
> But you won't get any points in LGM-SOC if you make PR's like this.
> First, you have to open an issue and ask the project admin to assign you that issue. Once you are assigned then make PR, and always mention the issue number in the PR description.

Ok Sir, No problem. This is not that type of error in which point to be given. I'm just understanding the instruction and project and I found that. Next time, I'll remember those points. Thank you!

**Comment by vishalps2606** [comment]
> If you want to score points then open an issue "Fix a typo error". Then edit your PR description with that issue number.
> 
> If you don't want to score points then tell me I will merge this PR.

Merge it! I don't want to earn a point on this issue. Thank you!

**Pull request merged**
