### PR TITLE
Integrated payment gateway in premium page 

### PR DESCRIPTION
**Pull request by kshitija-2001**
#### Issue Number
fixes #

ISSUE #359 

#### Describe the changes you've made
Integrated  Razorpay payment gateway in the premium page

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by kshitija-2001** [comment]
image
image
image

**Comment by QAZIMAAZARSHAD** [comment]
These payments are not real naa?

**Comment by kshitija-2001** [comment]
no they are in test mode

**Comment by QAZIMAAZARSHAD** [comment]
> no they are in test mode

Yaa, I clicked on pay with QR and a message popped your payment was received, then I received an email for payment confirmation. I was shocked that my 500 Rs are gone, I was relieved when I checked it on Razorpay and my account balance.

Haha.....


Good work @kshitija-2001.

**Comment by kshitija-2001** [comment]
Haha, thanks a lot!

**Pull request merged**
