### PR TITLE
Final changes to scrollbar

### PR DESCRIPTION
**Pull request by Cobaltmon**
#### Checklist
- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

https://cobaltmon.github.io/Movie-Streaming-Website/

### CODE REVIEW

**Comment by Cobaltmon** [comment]
If I messed up something, please let me know. I had some errors pushing it I have the error 'updates were rejected because the remote contains work that you do not have locally'

**Comment by QAZIMAAZARSHAD** [comment]
Share website link

**Comment by Cobaltmon** [comment]
https://cobaltmon.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
@Cobaltmon your repo is 15 commits behind fetch upstream.

**Pull request merged**
