### PR TITLE
revamp login page

### PR DESCRIPTION
**Pull request by Aditya7494**
ISSUE #180 
fixes #

I have added font awesome icon for email and password. I have also added option to login through facebook and instagram.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [*] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [*] All new and existing tests passed.
- [*] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Aditya7494** [comment]
Screenshot (301)

**Comment by QAZIMAAZARSHAD** [comment]
@Aditya7494 are these working, login using Facebook?

**Comment by Aditya7494** [comment]
@QAZIMAAZARSHAD I have just designed these icons using html, css and font awesome.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I have just designed these icons using html, css and font awesome.

Okay so these are not working, fine.

Resolve conflicts.

**Comment by Aditya7494** [comment]
@QAZIMAAZARSHAD Where to commit?
Master branch or new branch?

**Comment by QAZIMAAZARSHAD** [comment]
The branch with which ou are making PR.

**Pull request closed without merging**
