### PR TITLE
Manage profile

### PR DESCRIPTION
**Pull request by shivshankar9**
#361

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
I think you have missed web series, tv, movies, premium, and few other pages.

Also, change manage profile to "My Profile".

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 any updates.

**Comment by shivshankar9** [comment]
Tommorow I will try to make or

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link also when you are done. So I can review your changes.

**Comment by shivshankar9** [comment]
https://shivshankar9.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
image

Correct all navbars. Also, add scroll to top button in profile page.

**Comment by shivshankar9** [comment]
Please open others issue for this, because of my exams load unable to make contribution
I need some time to fix
Also if you wish ,you can close this PR I have no issue with that..

**Comment by QAZIMAAZARSHAD** [comment]
Take your time.

**Pull request closed without merging**
