### PR TITLE
Changing title of the Website

### PR DESCRIPTION
**Pull request by Sourav61**
Issue #17 

#### Describe the changes you've made
Changed the title of the website from ApnaTheatre.com to ApnaTheatre

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Sourav61 fetch upstream from main repository because your PR are making few changes in Readme file as well.

**Comment by QAZIMAAZARSHAD** [comment]
No, you can see yourself in changes.

375 additions and 375 deletions.

**Comment by QAZIMAAZARSHAD** [comment]
These changes are not helping @Sourav61. Google it or watch some youtube videos to resolve it.

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD sir now is it fine, it shows 2 additions and 363 subtractions!!

**Pull request closed without merging**
