### PR TITLE
Form validation added and content overlapping in input fields fixed

### LINKED ISSUE #412: Add validation to the form in contactus.html
Adding validation and preventing the collapsing of email on the input.

Untitled

### PR DESCRIPTION
**Pull request by Sarthakjain594**
#### Describe the changes you've made
So I have made some changes in CSS file in order to rectify the input fields behaviour on focus and in filled state . Also , added the suitable js code for form validation as per the directions . 

#### Deploy your changes to github page or netlify and mention deployment link:
https://sarthakjain594.github.io/Movie-Streaming-Website/

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
NA

#### Test plan (OPTIONAL)
Test by filling out the fields and submitting and by leaving them empty alltogether and individually as well . 

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
- [x] LGMSoc

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Few mistakes!!

First name and last name should accept only alphabets, these are accepting numbers as well as special characters.
Instead of "enter your phone details" prompt should be "phone number should be 10 digits".
And email has not been validated. It is getting accepted without @gmail.com.
Also, there are 2 prompts for the email field, there should be only one remove the old prompt.

**Comment by QAZIMAAZARSHAD** [comment]
And your repo is not updated fetch upstream.

**Comment by Sarthakjain594** [comment]
okay sorry  for inconvenience . Let me correct all these mistakes .

**Comment by Sarthakjain594** [comment]
I have made the requested changes . Also , wanna mention that I haven't made last name as a mandatory field because not everybody prefer that and if in case someone will fill it then only alphabets will be allowed .

**Comment by QAZIMAAZARSHAD** [comment]
> I have made the requested changes . Also , wanna mention that I haven't made last name as a mandatory field because not everybody prefer that and if in case someone will fill it then only alphabets will be allowed .

Fine.
I never mentioned the last name to be mandatory, but it should accept only alphabets.

**Comment by Sarthakjain594** [comment]
> > I have made the requested changes . Also , wanna mention that I haven't made last name as a mandatory field because not everybody prefer that and if in case someone will fill it then only alphabets will be allowed .
> 
> Fine.
> I never mentioned the last name to be mandatory, but it should accept only alphabets.

ya ya I know that , but just wanna inform once .

**Comment by QAZIMAAZARSHAD** [comment]
Still, one mistake.

The phone number field should accept exactly 10 digits but it is accepting more than 10 digits. Also, correct the message, you forgot to write 10.

**Comment by Sarthakjain594** [comment]
> Still, one mistake.
> 
> The phone number field should accept exactly 10 digits but it is accepting more than 10 digits. Also, correct the message, you forgot to write 10.

ohh , okay doing .

**Comment by Sarthakjain594** [comment]
What alert msg should I put if someone tries to enter alphabets instead of numbers in phone number ?

**Comment by Sarthakjain594** [comment]
heyy , I hope it should work now . @QAZIMAAZARSHAD

**Pull request merged**
