### PR TITLE
relevant hover changes done on kids and web-series

### PR DESCRIPTION
**Pull request by abhshkvrm**
#### Issue Number
fixes #

ISSUE #241
#### Describe the changes you've made
Hovering effect on cards in web-series page and kids page

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
NA

#### Test plan (OPTIONAL)
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Can't review, too many additions and deletion. Update your repo.

Only necessary changes should highlight.

**Comment by abhshkvrm** [comment]
it was the same file that i have pushed earlier, as you have said the red header thing is fine. I have also added that when you will merge i guess it will over write, rest everything is same as I have done earlier.

**Comment by QAZIMAAZARSHAD** [comment]
> it was the same file that i have pushed earlier, as you have said the red header thing is fine. I have also added that when you will merge i guess it will over write, rest everything is same as I have done earlier.

No this is not how pull request works.

You can see in the files changed section, how many additions and deletions your PR is causing it may overwrite existing features and disturb the entire website.

Fetch upstream update your repo then make changes then make PR.

**Comment by abhshkvrm** [comment]
okay then just open it i will do only the required changes sorry for the error.

**Comment by QAZIMAAZARSHAD** [comment]
Make new PR that will be easy.

**Pull request closed without merging**
