### PR TITLE
Design recommendation page

### LINKED ISSUE #60: Recommendation page
Recommendation or mood page which will suggest movies according to the mood

### PR DESCRIPTION
**Pull request by kshitija-2001**
#### Issue Number
fixes #60 

ISSUE #60 

#### Describe the changes you've made
A mood page is made by adding funny movies, sad, energetic movies.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] LGMSOC21

### CODE REVIEW

**Comment by kshitija-2001** [comment]
we need to add it in the nav bar

**Comment by QAZIMAAZARSHAD** [comment]
> we need to add it in the nav bar

Obviously, name it 'My recommendations'.

**Comment by QAZIMAAZARSHAD** [comment]
Add it in the navbar of every single page.

**Comment by kshitija-2001** [comment]
Ok i will make the changes

**Comment by kshitija-2001** [comment]
Done updating all the nav bar.

**Comment by QAZIMAAZARSHAD** [comment]
Check responsiveness in both mobile and desktop views.

Share screenshot.

**Comment by QAZIMAAZARSHAD** [comment]
Navbar is disoriented.

Looks like you have used a different font use the one which is used in other pages.

Change the line "movie suggestion by feeling and ....." to "My Recommendations".

And if 'my recommendation' doesn't fit in the nav bar use something else.

**Comment by kshitija-2001** [comment]
Capture


I named it mood still the navbar is disoriented

**Comment by kshitija-2001** [comment]
and search bar is also working

**Comment by QAZIMAAZARSHAD** [comment]
> Capture
> 
> I named it mood still the navbar is disoriented

Try fixing it

**Comment by QAZIMAAZARSHAD** [comment]
@kshitija-2001 just remove recommendations from the navbar and add it with other genres in the drop down list.

**Comment by saimanoharhm** [comment]
@kshitija-2001 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by QAZIMAAZARSHAD** [comment]
@kshitija-2001 any updates?

**Comment by kshitija-2001** [comment]
yes working on it!

**Comment by QAZIMAAZARSHAD** [comment]
@kshitija-2001 this PR is open since 21 days.

Website has been updated.
I am closing this PR.


Just add my recommendation page in the genres drop-down list.

**Pull request closed without merging**
