### PR TITLE
Fixing Header font-size on card Flip

### LINKED ISSUE #323: Title, description, and buttons inside movie cards not aligned properly
name of the interstellar card  while flip
card flip time duration button size 
the layout of the all card in fantasy file can be 3 to 4 per raw with certain padding

### PR DESCRIPTION
**Pull request by priyansh11786**
#### Describe the changes you've made
To resolve the assigned issue I have made changes in the home.html file, specifically I have assigned font-sizes to h1 heading(line no. 1826) and h1 heading(line no. 1954) of poster component inside 'third-block' container component.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot (28)

Screenshot (29)

Screenshot (31)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] DevIncept Contribution Program

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@priyansh11786 check every single card of every page and do the changes.

Also, check few cards are not redirecting to the trailer of the movie.
Correct it as well.

**Comment by priyansh11786** [comment]
Sure I will check for every detail mentioned above and try to incorporate related changes.

**Comment by priyansh11786** [comment]
@QAZIMAAZARSHAD I have checked & fixed the Content alignment in the movie card of each and Every page and have also fixed the Trailer redirecting issue on cards where it existed

**Comment by QAZIMAAZARSHAD** [comment]
@priyansh11786 check the trailer on the horror and documentary page once.

Make one more PR to correct the issue.

**Comment by QAZIMAAZARSHAD** [comment]
@priyansh11786 don't fill the google form until your PR has label on it.

I have awarded you points but you still need to correct the above suggested issue.
Resolve it soon.

**Comment by priyansh11786** [comment]
> @priyansh11786 check the trailer on the horror and documentary page once.
> 
> Make one more PR to correct the issue.

I have checked for trailer redirecting issue in both the pages earlier in the previous commit, Can you be more specific about which card you are talking about in the horror and documentary page

**Comment by QAZIMAAZARSHAD** [comment]
In horror - Get out, a quite place
In documentary - last three

**Pull request merged**
