### PR TITLE
Added a movie page

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
#### Issue Number
fixes #

ISSUE #163 
-->

#### Describe the changes you've made
Added a movie page with a slider and 5 categories of movies

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
NA

#### Test plan (OPTIONAL)
Click on it 

#### Checklist

- [x ] I have added my name in the contributors list at the end of README.md file.
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@anushka-srivastava22 you forgot to link the movie page with other pages.

Do it.

**Comment by anushka-srivastava22** [comment]
I tried linking the movies page. And made several pull request searched it on net. Tried all ways and did for 25 hours approx till now but i am not been able to resolve the conflicts even if I do so first it shows -14 and then go down to -1236. Mentors even one responded that way I have tried many times.

**Comment by QAZIMAAZARSHAD** [comment]
I have merged it now create a separate issue to link it with other pages.

**Comment by anushka-srivastava22** [comment]
Okayyy Sir. And I will search the issue more on YouTube and internet

**Comment by QAZIMAAZARSHAD** [comment]
Also, you have added the old logo and old footer, the search bar is also functional now.

Update everything, new logo, new footer, functional search bar, scroll to top button, responsiveness, everything should be present.

I have not added a level and lgmsoc label for this PR because it is incomplete, I will add level  and lgmsoc labelwhen you solve these in another issue.

**Comment by QAZIMAAZARSHAD** [comment]
Open new issue to resolve this. And ask me to assign you.

**Comment by anushka-srivastava22** [comment]
Okayyy sir

**Pull request merged**
