### PR TITLE
Fix The Footer Of FAQ Page

### LINKED ISSUE #390: Fix the footer of FAQ page

### PR DESCRIPTION
**Pull request by Garima-7**
Fixed #390

#### Describe the changes you've made
Align the elements of footer correctly.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Screenshot of Footer
Footer

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Looks like there is still too much gap.

Make it similar to other footers.

**Comment by Garima-7** [comment]
> Looks like there is still too much gap.
> 
> Make it similar to other footers.

Can you pls brief which space are you talking about(left,right,bottom,top)?

**Comment by QAZIMAAZARSHAD** [comment]
The space between follow us and links, space between contact us and feel free to reach.

Compare the footer of the faq page with others, it should be similar.

**Comment by QAZIMAAZARSHAD** [comment]
Also share link of website when you are done.

**Comment by Garima-7** [comment]
[
Footer
](url)

Is it fine now?

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 nothing has changed 

image


Correct it

**Comment by QAZIMAAZARSHAD** [comment]
Fix the issue.

Make new PR.

**Comment by Garima-7** [comment]
ok sir will make new PR.

**Comment by Garima-7** [comment]
maybe in this PR changes are not shown.

**Comment by QAZIMAAZARSHAD** [comment]
Fine now.

Don't forget to fill google form

**Comment by Garima-7** [comment]
> Fine now.
> 
> Don't forget to fill google form.
> Mention this link which has DCP label

ok sir 👍

**Pull request merged**
