### PR TITLE
updated files

### PR DESCRIPTION
**Pull request by Anjali1806**
I have updated some spelling mistakes, punctuations .

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
**6.** Always take a pull from the upstream repository to your master branch to keep it at par with the main project(updated repository). This line is correct it is (at par).

This movie streaming website allows users to watch their favorite movies, tv shows, and web series from multiple genres like crime, comedy, drama, kids, etc.

And tv page is yet to be created so tv shows is also fine. And both spellings of 'favorite' are fine.


Change these two lines again and I will merge your PR.

Also, always mention the issue number in the PR description like this -> #149. And first, get yourself assigned then only make PR.

**Comment by Anjali1806** [comment]
# Movie Streaming Website  🎬

Are you a movie maniac, who loves to binge watch awesome series? If Yes, then you have come to right place.
<p align="center"></p>

Everyone loves to watch their favorite shows with friends and some snacks. But there is something that you might be missing out on!
<p align="center"></p>

So, what else do you need?🤔.
<p align="center"></p>

Here is the answer: An awesome movie streaming website of yours that has all your favorites at one place! 
<p align="center"></p>

We already have Netflix, Prime and Hotstar but they might be expenive sometimes. So what should we do? You must be wondering that making our own movie website might take time, require some web development knowledge and still you might get something really cool. 
<p align="center"></p>

Well! Take a chill pill. Don't be intimidated by those thoughts. __Apna Theatre Website__ is here for the rescue!
<p align="center"></p>

## A sneek peek into what we have here🙈 :

### Home Page:
<p align="center"></p>

### Seperate Page for All Genres:
<p align="center"></p>

## About

<<<<<<< Updated upstream
ApnaTheatre.com is a place for all movieocohlic's to enjoy. This movie streaming website allows users to watch their favorite movies, tv shows and web series from multiple genres like crime, comedy, drama, kids etc. 
=======
ApnaTheatre.com is a place for all movieocohlic's for entertainment. This movie streaming website allows users to watch their favourite movies,tv shows and web series from multiple genres like crime, comedy, drama, kids etc. 
>>>>>>> Stashed changes

## Link to the website
https://qazimaazarshad.github.io/Movie-Streaming-Website/

## Tech Stack



## How to get started❓

You can refer to the following articles on the basics of Git and Github and also contact the Project Mentors, in case you are stuck:

- If you don't have git on your machine, [install](https://help.github.com/articles/set-up-git/) it.
- [Watch this video to get started, if you have no clue about open source](https://youtu.be/SL5KKdmvJ1U)
- [Forking a Repo](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
- [Cloning a Repo](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository)
- [How to create an Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/creating-an-issue)
- [How to create a Pull Request](https://opensource.com/article/19/7/create-pull-request-github)
- [Getting started with Git and GitHub](https://towardsdatascience.com/getting-started-with-git-and-github-6fcd0f2d4ac6)

## Contribution Guidelines 🏗

Are we missing any of your favorite features, which you think you can add to it❓ We invite you to contribute to this project and improve it further

To start contributing, follow the below guidelines: 

**🌟.**  Star🌟 the project to bookmark and appreciate the work.

**0.**  Take a look at the existing [issues](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues) or create your own issues. Wait for the Issue to be assigned to you after which you can start working on it.

**1.**  Fork [this](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website) repository.

**2.**  Clone your forked copy of the project.

```
git clone --depth 1 https://github.com/<your_user_name>/Movie-Streaming-Website.git
```

**3.** Navigate to the project directory :file_folder: .

```
cd Movie-Streaming-Website
```

**4.** Add a reference(remote) to the original repository.

```
git remote add upstream https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website.git 
```

**5.** Check the remotes for this repository.

```
git remote -v
```

**6.** Always take a pull from the upstream repository to your master branch to keep it at par with the main project(updated repository).

```
git pull upstream master
```

**7.** Create a new branch.

```
git checkout -b <your_branch_name>
```

**8.** Perform your desired changes to the code base.

<p align="center"></p>

**9.** Track your changes:heavy_check_mark: .

```
git add . 
```

**10.** Commit your changes .

```
git commit -m "Relevant message"
```

**11.** Push the committed changes in your feature branch to your remote repo.

```
git push -u origin <your_branch_name>
```

**12.** To create a pull request, click on `compare and pull requests`. Please ensure you compare your feature branch to the desired branch of the repo you are suppose to make a PR to.

**13.** Add appropriate title and description to your pull request explaining your changes and efforts done.

**14.** Click on `Create Pull Request`.

**15.** Voila :exclamation: You have made a PR to the Apna Theatre project :boom: . Sit back patiently and relax while the project maintainers review your PR. Please understand, at times the time taken to review a PR can vary from a few hours to a few days.

<p align="center"></p>

## Project Admin👨‍:

<p align="center">

</p>

<a href="https://www.linkedin.com/in/qazi-maaz-arshad/">
<h5 align="center"><b>Qazi Maaz Arshad</b></a>

## Open Source Programs we have been associated with: 

<p align="center">
<a href="https://letsgrowmore.in/soc/" target="_black"></a>
</p>

## Code of Conduct
<p align="center"></p>
<a href="https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/CODE_OF_CONDUCT.md">
<h5 align="center"><b>Click to read</b></a>
  
## License 
<p align="center"></p>
<a href="https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/LICENSE">
<h5 align="center"><b>MIT License</b></a>

**Comment by QAZIMAAZARSHAD** [comment]
> **6.** Always take a pull from the upstream repository to your master branch to keep it at par with the main project(updated repository). This line is correct it is (at par).
> 
> This movie streaming website allows users to watch their favorite movies, tv shows, and web series from multiple genres like crime, comedy, drama, kids, etc.
> 
> And tv page is yet to be created so tv shows is also fine. And both spellings of 'favorite' are fine.
> 
> Change these two lines again and I will merge your PR.
> 
> Also, always mention the issue number in the PR description like this -> #149. And first, get yourself assigned then only make PR.
> 
> You have not even opened an issue. First, open and ask me to assign you.

You ignored this.

**Comment by Anjali1806** [comment]
I have posted new issue, just ignore this and sorry for the inconvenience.

**Pull request closed without merging**
