### PR TITLE
TV page

### PR DESCRIPTION
**Pull request by SanjeevKumar22**
#### Issue Number
fixes #

ISSUE #37
#### Describe the changes you've made
Navbar and footer styling
TV Page styling

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
Try to resolve conflicts.

**Comment by SanjeevKumar22** [comment]
Resolved

**Comment by QAZIMAAZARSHAD** [comment]
Again conflicts

**Comment by SanjeevKumar22** [comment]
Solved

**Comment by QAZIMAAZARSHAD** [comment]
@SanjeevKumar22 you have changed so many things.

Added blue color, destroyed the theme of the website.
Made navbar fixed, uneccesaary changes.

I cannot merge this.

Redesign again.

**Comment by SanjeevKumar22** [comment]
Then assign the issue i will work on that

**Comment by QAZIMAAZARSHAD** [comment]
> Then assign the issue i will work on that

Look for any issue on which you want to work and ping me.
I'll assign you.

**Pull request closed without merging**
