### PR TITLE
ISSUE#49 - Fixed overlapping footer issue

### PR DESCRIPTION
**Pull request by WayneHaworth**
Removed the negative top margin and added a positive margin, which adds a little space.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@WayneHaworth I have reviewed your PR it is fine.

Bur this is not how you make pull requests.
First, you have to ask the project admin to assign you that particular issue. Once assigned then you can work on it.
Also, you have to always mention the issue number in the PR description like #49. So that hashtag turns blue.

If you don't follow the contribution guidelines then you might not get points for your work.

**Comment by WayneHaworth** [comment]
My apologies, it is my first time.

**Comment by QAZIMAAZARSHAD** [comment]
@WayneHaworth ping me in the issue 49 thread so I can assign it to you.

**Comment by WayneHaworth** [comment]
Closing as a new pull request has been actioned with better changes.

**Pull request closed without merging**
