### PR TITLE
Aasthasaxena217/movie streaming website

### LINKED ISSUE #491: Modify hover effect of cards on the premium page
When we hover on the cards, they move slightly in right direction , they are very close to each other. We can make a little smaller or proper hovering effect.
image

### PR DESCRIPTION
**Pull request by aasthasaxena217**
#### Fixes #491 
Fixes #491 

 

#### Describe the changes you've made
I have changed and removed the bug of hover effect of pricing cards on Premium page. Cards will zoom and will not effect other cards.

#### Deploy your changes to github page or netlify and mention deployment link:
Deployment Link : https://aasthasaxena217.github.io/Movie-Streaming-Website/premium.html 

Open Source program: LGM-SOC

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts. Fetch upstream.

The premium page has been updated.

**Comment by aasthasaxena217** [comment]
I have resolved conflicts , do I need to now anything?

**Comment by QAZIMAAZARSHAD** [comment]
@aasthasaxena217 its messed up.

Check your website in mobile view.

Compare with the original website.

Then make the changes.

**Comment by aasthasaxena217** [comment]
Can you please check :
https://aasthasaxena217.github.io/Movie-Streaming-Website/premium.html

**Pull request merged**
