### PR TITLE
Production branch

### PR DESCRIPTION
**Pull request by rushikadivar**
#### Issue Number
fixes #

ISSUE #323 

#### Describe the changes you've made
the scrollbar at the end takes too much time to reflect to top
scrollbar are relative positioned and need to be fixed positioned and it should be hidden in top of the page and aftersome scrolling it will be visible

footer fonts are too large need to be small
movies card title's spacing are changed and the some movies link to trailer should be appropriate

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@rushikadivar always mention the issue number in the PR description.

And PR title and description should describe the changes and related issues, I cannot understand which issue you have solved.

Edit your PR description.

**Comment by rushikadivar** [comment]
It has been updated now, Plesae check and review it

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.

**Comment by QAZIMAAZARSHAD** [comment]
@rushikadivar Resolve conflicts.

Fetch upstream.

**Comment by rushikadivar** [comment]
I changed the files style tag, inside that the only difference is in scrollbar css and I only changed the position and the spacing but still it shows the conflicts to the master branch. Please have a look on that

**Comment by QAZIMAAZARSHAD** [comment]
> I changed the files style tag, inside that the only difference is in scrollbar css and I only changed the position and the spacing but still it shows the conflicts to the master branch. Please have a look on that

To resolve conflicts you have to fetch upstream.

**Comment by QAZIMAAZARSHAD** [comment]
This branch is 4 commits ahead, 30 commits behind QAZIMAAZARSHAD: master.


Your branch is 30 commits behind the main branch. Fetch upstream to make it even with the main branch.


Make a new PR after updating your repo, with only necessary changes.

**Pull request closed without merging**
