### PR TITLE
Improvements readme

### PR DESCRIPTION
**Pull request by shivshankar9**
#332

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 the size of the gif is very large, compress it.

Do it fast. And make PR.

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 are you on it.

Resolve this ASAP, it is consuming too much data.

**Comment by shivshankar9** [comment]
Yes

**Comment by shivshankar9** [comment]
Files taking time to compress

**Pull request merged**
