### PR TITLE
Added Cursor While Hovering On The Movies (#114)

### PR DESCRIPTION
**Pull request by JatanDudeja**
Issue : #114

**Changes Done :**

1. Added pointer cursor to all the movies when hovered.
2. Changed id of web series from id = "Web Series" to id = WebSeries.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by JatanDudeja** [comment]
Okay will do it soon. 👍🏻

**Comment by QAZIMAAZARSHAD** [comment]
I am closing this PR.
Fetch upstream and do only the necessary changes.

If the problem still persists reach out to mentors in the slack channel.

**Comment by JatanDudeja** [comment]
Okay I will follow all the steps. Thans for the cooperation.

**Pull request closed without merging**
