### PR TITLE
Solve scrollbar changes pr373

### PR DESCRIPTION
**Pull request by Cobaltmon**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist
- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Testing link: https://cobaltmon.github.io/Movie-Streaming-Website/home.html

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
No, not that.

The effect is fine on every page.


Make it like before. 
Change the effect only on movies, web series, and kids pages and make them like other pages.

**Comment by Cobaltmon** [comment]
Oh that. Understood

**Comment by Cobaltmon** [comment]
Hi. Can you check if its been corrected?

**Comment by QAZIMAAZARSHAD** [comment]
Nope.

Check this is current effect https://qazimaazarshad.github.io/Movie-Streaming-Website/crime.html.

All scroll bars should be like this. Only movies, web series, and kids pages are different make them similar.

**Comment by QAZIMAAZARSHAD** [comment]
I suggest create a new PR.

**Pull request closed without merging**
