### PR TITLE
redirect to quiz.html after successful signup

### LINKED ISSUE #347: Not redirecting to quiz.html after successful sign up

### PR DESCRIPTION
**Pull request by dilroseR**
#### Fixes #(issue number)

 Fixes #347 

**Changes I've made:**
I've made changes in such a way that after successful signup, the user is redirected to quiz.html which wasn't happening before

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) DevIncept Contributions

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@dilroseR working now.

But 2 alerts are showing.

Remove the simple alert. Only the sweet alert should appear.

Make one more PR to correct it.

**Comment by dilroseR** [comment]
> @dilroseR working now.
> 
> But 2 alerts are showing.
> 
> Remove the simple alert. Only the sweet alert should appear.
> 
> Make one more PR to correct it.

new pr after removing alert?

**Comment by QAZIMAAZARSHAD** [comment]
Yes remove simple alert, only sweet alert should be there.

**Comment by dilroseR** [comment]
> Yes remove simple alert, only sweet alert should be there.

alright

**Comment by dilroseR** [comment]
> Yes remove simple alert, only sweet alert should be there.

for PR which number should i give?

**Comment by QAZIMAAZARSHAD** [comment]
347

**Comment by dilroseR** [comment]
> 347

I've created PR. kindly check

**Comment by QAZIMAAZARSHAD** [comment]
Fill the google form and mention this PR link which has dcp label.

**Comment by dilroseR** [comment]
> Fill the google form and mention this PR link which has dcp label.

👍

**Pull request merged**
