### PR TITLE
Movie pages according to different languages

### PR DESCRIPTION
**Pull request by nandinimalik16**
ISSUE #36  -->

#### Describe the changes you've made
Dropdown menu added to the navbar in Movies and two pages for English and hindi movies are added.On hovering on movies in navbar it will show two options hindi and English , onclicking them we will reach the respective pages

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
By hovering on Movies on Navbar

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
ApnaTheatre _ Web Series — Mozilla Firefox 7_9_2021 3_39_39 AM
ApnaTheatre _ Web Series — Mozilla Firefox 7_9_2021 3_39_30 AM
ApnaTheatre _ Web Series — Mozilla Firefox 7_9_2021 3_39_21 AM
demo-link:  https://nandinimalik16.github.io/Movie-Streaming-Website/

- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
Lets Grow more SOC'21

### CODE REVIEW

**Comment by saimanoharhm** [comment]
Looks good. 
cc : @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@nandinimalik16 share a demo link to your website.

Also mention the issue number in the PR description.

**Comment by nandinimalik16** [comment]
okay

**Comment by nandinimalik16** [comment]
> 
> 
> @nandinimalik16 share a demo link to your website.
> 
> Also mention the issue number in the PR description.

I mentioned the PR and demo Link now. Please check it any changes are needed.

**Comment by QAZIMAAZARSHAD** [comment]
@nandinimalik16 there are plenty of mistakes.

Screenshot (30)
Screenshot (27)
Screenshot (28)


Also, movie cards should be like this.
Screenshot (29)

**Comment by nandinimalik16** [comment]
I have tried to fix the mistakes. Kindly check once more


> 
> 
> @nandinimalik16 there are plenty of mistakes.
> 
> Screenshot (30)
> Screenshot (27)
> Screenshot (28)
> 
> Also, movie cards should be like this.
> Screenshot (29)

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts and share the website link so I can review your changes.

**Comment by nandinimalik16** [comment]
Apna Theater_Hindi Movies — Mozilla Firefox 7_9_2021 7_46_15 PM
Apna Theater_Hindi Movies — Mozilla Firefox 7_9_2021 7_46_24 PM
Apna Theater_Hindi Movies — Mozilla Firefox 7_9_2021 7_46_34 PM
Apna Theater_Hindi Movies — Mozilla Firefox 7_9_2021 7_46_44 PM

**Comment by nandinimalik16** [comment]
> 
> 
> Resolve conflicts and share the website link so I can review your changes.

ok

**Comment by nandinimalik16** [comment]
demo link: https://nandinimalik16.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
@nandinimalik16 check the following:

footer (lots of space at the bottom also fix the scroll to top button in footer)
Tv Page
Anime page
Movies page

**Comment by nandinimalik16** [comment]
> 
> 
> @nandinimalik16 check the following:
> 
> footer (lots of space at the bottom also fix the scroll to top button in footer)
> Tv Page
> Anime page
> Movies page
> Also, black image when sliding the slider.

I have fixed these issues, please review them
demo link: https://nandinimalik16.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
Check the navbar on the premium page.
Check slideshow in Hindi and English page.
Check horizontal scroll bar in Hindi page.

**Comment by QAZIMAAZARSHAD** [comment]
@nandinimalik16 still working on it or should I close this PR?

**Comment by nandinimalik16** [comment]
I am still working.
will submit the updates by tomorrow

**Comment by QAZIMAAZARSHAD** [comment]
@nandinimalik16 any updates?

Make new PR when you are done. Fetch upstream then push changes.

**Pull request closed without merging**
