### PR TITLE
Fixed inverted label text while flipping the poster

### LINKED ISSUE #521: Flipping Card will also invert the Label of the movie
When hovering over the poster, the label of the poster flips with the card.

Now - 
image

How it should be - 
image

Verify on all the pages (all genres pages).

### PR DESCRIPTION
**Pull request by vydyas**
#### Fixes #521 

 
Screenshot 2022-10-01 at 12 12 31 AM

#### Describe the changes you've made
Seperated label div from flipping div and kept it in outside the flipping div.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ x] I have mentioned related issue number in PR description.
- [x ] I have added screenshots and related demo links of my changes..
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@vydyas please share a live demo link of website. So I can review the changes.

**Comment by vydyas** [comment]
https://user-images.githubusercontent.com/2999586/193337340-cfa490d1-aad1-4fd7-b42e-0448a4955d76.mp4

@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Looks fine. 👍
Will merge in the morning. 

But everytime you make any PR, host your branch on GitHub pages and share link. 
That makes it easy to review.

**Comment by vydyas** [comment]
@QAZIMAAZARSHAD  thanks for reviewing.

https://vydyas.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
@vydyas 
image
image


Check.

The footer is disturbed/ Also, only 3 movie cards are displayed in one line instead of 4.

Compare with https://qazimaazarshad.github.io/Movie-Streaming-Website/home.html

**Comment by vydyas** [comment]
good observation @QAZIMAAZARSHAD . Fixed in a new commit

**Pull request merged**
