### PR TITLE
add tv sections

### PR DESCRIPTION
**Pull request by ZeTheDeveloper**
#### Describe the changes you've made
Added sections of popular, top picks, featured into tv.html. Also added carousel view at top of the web page.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Link: https://zethedeveloper.github.io/Movie-Streaming-Website/tv.html

image
image

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x ] I have mentioned related issue number in PR description.
- [x ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here: https://github.com/Ayushparikh-code/Web-dev-mini-projects)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@ZeTheDeveloper please share a live demo link of your website, so I can review the changes.

**Comment by ZeTheDeveloper** [comment]
https://zethedeveloper.github.io/Movie-Streaming-Website/tv.html here is the demo link

**Comment by QAZIMAAZARSHAD** [comment]
@ZeTheDeveloper you have disabled the search function.
Check!!!
image


Also, update the title bar
Screenshot (354)

**Comment by ZeTheDeveloper** [comment]
Hi I have made the necessary changes, pls check again

**Pull request merged**
